### ISSUE TITLE
I have a question, not really an issue 

### ISSUE THREAD

**Issue by lambertwen** [Neufund/TypeChain#22]
Hi,

I have been trying to use Angular 5 interact with solidity contracts for a couple of weeks. It was a pin in my butt. Anyway, found out the article you posted in Dec last year and would like to give typechain a shot. However, I installed typechain following steps with this git post,

npm install --save-dev typechain
yarn add --dev typechain

and got "typechain: command not found" (ubuntu 16.04). 

Your instruction also says that "you might need to make sure that it's available in your path if you installed it only locally". But how? ( Sorry, I am neither an JS stack nor a ubuntu expert) I could not find typescript command anywhere in the system. 

Please help! This is my last attempt to salvage my Angular Blockchain project. Otherwise I would switch to React framework which is a way simpler to communicate with solidity contracts.

Thanks for your help in advance!
Calibre

**Comment by krzkaczor** [comment]
Hey @lambertwen,
so you need to make sure that type chain (installed in your local `node_modules`) is available in your shell. To avoid this issue you can simply run `./node_modules/.bin/typechain`. Or create a script in `package.json` that uses typechain (npm/yarn makes sure that packages from node_modules/.bin) are available in PATH.

More reading: http://2ality.com/2016/01/locally-installed-npm-executables.html
Good luck!

**Comment by lambertwen** [comment]
You are the man. Thanks ... Krzkaczor.

I am excited to explore typechain. Might bug you about interacting with solidity event using typechain. 

Thanks again.
Lambert

**Comment by lambertwen** [comment]
question closed.

**Comment by krzkaczor** [comment]
@lambertwen, Typechain doesn't support events for now :( I have initial implementation half-baked locally but there is still some work to be done.

**Comment by lambertwen** [comment]
@krzkaczor I am sorry to hear that. I will go back to my backup plan using React for now. Definitely thump up for what you have done. I am going to keep a close eye on typechain and looking forward to using it with event support. No pressure though, lol.

Have a nice day!
Lambert
