### ISSUE TITLE
Possibility to look in node_modules for abi files

### ISSUE THREAD

**Issue by davidfarina** [Neufund/TypeChain#32]
It would be great to have the possibility to specify one or more npm packages where typechain will look for abi's.

Until now, we have different projects for DAPP and contracts and include the abis as an npm package to make it easier to reference the contracts, instead of pointing outside the project. Makes it less a hassle when working with CI tools to just package the contracts and include them in node_modules. Its also more adaptable when on different systems/machines etc.

I am somehow not able to put an enhancement tag to this issue so please forgive me that.

**Comment by krzkaczor** [comment]
I think you should be able to accomplish it by using custom glob as mentioned in readme:
`typechain "./node_modules/(packageA|packageB)"` (we use https://www.npmjs.com/package/glob)
Have you tried it?

**Comment by krzkaczor** [comment]
I can confirm that it works. Just specify `outDir` to push all contracts in one place: 

```typechain --outDir app/lib/contracts "./node_modules/neufund-contracts/build/contracts/*.json"```
