### ISSUE TITLE
What about events?

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [Neufund/TypeChain#37]
Correct me if I'm wrong, but Iv'e not seen any code generated from events in the abi. Would be an awesome feature to have an `rxjs.Observable` generated for each event.

**Comment by dev-matan-tsuberi** [comment]
A callback should be enough.

**Comment by krzkaczor** [comment]
Support for events was merged and published as: `0.2.0`. Discussion about rxjs and typechain: https://github.com/Neufund/TypeChain/issues/47
