### ISSUE TITLE
createAndValidate passes for non-existent contract with MetaMask

### ISSUE THREAD

**Issue by Levino** [Neufund/TypeChain#50]
When the contract does not exist at the specified address the `web3` instance from MetaMask will return `0x` and not `0x0` for the call to `web3.eth.getCode`. So `createAndValidate` does not throw an error. The check [here](https://github.com/Neufund/TypeChain/blob/ef4468caf20d5f5eaed02b1e4bbe90cc579b49e2/lib/generateSource.ts#L38) checks for `0x0`.

I was not able to verify what the expected behaviour of `web3` is. Will research another day.

**Comment by krzkaczor** [comment]
Yeah, i noticed that behaviour as well. Fix is super easy — we need to check for both. I am gonna prepare it in a sec.
