### ISSUE TITLE
Announcement! new web server released GAPI! Thank you TypeChain! :)

### ISSUE THREAD

**Issue by Stradivario** [Neufund/TypeChain#51]
Hello there guys i am in love with TypeChain and i decided to integrate it with my framework it is called @Gapi and you can find more information about the whole namespace here: 
https://github.com/Stradivario/gapi

Gapi-Ethereum module is part of this namespace and it can be found at this repository:
https://github.com/Stradivario/gapi-ethereum

The main idea behind this Framework is to provide Angular 2+ environment where you can write singleton typescript classes with Dependency Injection and many more features you can read about inside repo readme.It is using GraphQL this is where the name come from GraphQL API aka. GAPI :))

If you want to use generated contracts from TypeChain you need to import them as follows also ABI's from truffle compilation to get the contract address when it is deployed to network.
```typescript
import { GapiModule } from '@gapi/core';
import { GapiEthereumModule } from '@gapi/ethereum';

// Raw TypeChain compiled contracts
import { Coin } from '../core/contracts/Coin';
import { CoinCrowdsale } from '../core/contracts/CoinCrowdsale';

// Raw json ABI's
const CoinCrowdsaleABI = require('../../../truffle-metacoin-example/build/contracts/CoinCrowdsale.json');
const CoinABI = require('../../../truffle-metacoin-example/build/contracts/Coin.json');

@GapiModule({
    imports: [
        GapiEthereumModule.forRoot({
            port: process.env.ETHEREUM_PORT || 8545,
            rpc: process.env.ETHEREUM_HOST || 'http://localhost',
            contracts: [
                {
                    contract: Coin,
                    abi: CoinABI
                },
                {
                    contract: CoinCrowdsale,
                    abi: CoinCrowdsaleABI
                }
            ]
        })
    ]
})
export class CoreModule { }
```

Regards,
Kristiyan Tachev

**Comment by krzkaczor** [comment]
@Stradivario cool stuff! I am gonna place a note about projects using Typechain in updated readme.

**Comment by Stradivario** [comment]
Thank you @krzkaczor i appreciate it !! :)) Hope you will have time and try it out! :)))

Have a great day/night!
Regards,
Kristiyan Tachev

**Comment by Stradivario** [comment]
@krzkaczor i think this combination Gapi + TypeChain + Ganache is one of the fastest integration to start working with Ethereum :D Great Job Guys!!!
