### ISSUE TITLE
Typechain doesn't find .json files

### ISSUE THREAD

**Issue by kdelwat** [Neufund/Typechain#8]
Hi! I'm running into an issue with generating typings for JSON files.

My contract ABIs have the extension `.json` rather than `.abi`. From the README I think I should be using a glob pattern like `typechain "build/contracts/*.json"`, but this doesn't find the files. If I rename the ABIs to the `.abi` extension, the same glob works.

Not sure if I'm using this correctly or not!

**Comment by krzkaczor** [comment]
Hey,
you use it correctly but `npm` has an old version. Once I release you will be able to provide your own glob pattern among other goodies.

**Comment by krzkaczor** [comment]
@kdelwat I just released new version `0.0.5`. Check it out, please. It should fix this problem.

**Comment by kdelwat** [comment]
That fixed it! Thanks
